retry_wait_time = 5

accept = ["200..=204", "429"]

max_retries = 5

exclude = [
    # staging server
    'https://staging-collab.zed.dev/',

    # slow and unreliable server
    'https://repology.org',

    # the flollowing links are rate limited or use bot detection and respond with 403 instead of 429
    'https://openai.com',
    'https://claude.ai/download',
    'https://www.perplexity.ai',
    'https://platform.deepseek.com',
    'https://console.anthropic.com',
    'https://platform.openai.com',
    'https://linux.die.net/man/1/sed',
    'https://allaboutcookies.org',
]
